### ISSUE TITLE
HM Winds of Anthos Tool

### ISSUE THREAD

**Issue by HarvestWinter** [corick/my-config-files#1]
Hello! Any plan to make HM Winds of Anthos Text Extractor? It's game for PC and Switch. It's hard to edit message_en. Thanks.

**Comment by necco-atsume** [comment]
Nope, probably not, since it's not really on my radar. Also, creating an issue on my dotfiles repo is not the best way to get in touch, since I don't really check my comments - I have my Fediverse profile in my bio and you can dm me there.  Cheers!
